### ISSUE TITLE
Gruppennamen dürfen nicht den selben namen haben.

### ISSUE THREAD

**Issue by Dscheksn** [Dscheksn/AddressBookHsHn#2]
TableViewGroup irgendwelche checks die das verhindern hinzufügen

**Comment by Cod3Monky** [comment]
Gruppennamen werden nun nicht über die ID gecheckt, sondern über eigens dafür erstellte Objekte verglichen. ID check hab ich über cgu nicht gefunden O_o läuft so aber^^
